apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: conv-api
          image: aantonlarichev/conv-api:1.0
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: convapp-secret
                  key: SEED_USERNAME
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: convapp-secret
                  key: SEED_USER_PASSWORD
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: convapp-secret
                  key: AMQP_HOSTNAME
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: convapp-secret
                  key: AMQP_EXCHANGE
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: api-data
              mountPath: /opt/app
              subPath: uploads
      volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: api-pvc
  