apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-service-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      components: converter
  template:
    metadata:
      labels:
        components: converter
    spec:
      containers:
        - name: conv-service
          image: antonlarichev/conv-service:1.0
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: convapp-secret
                  key: SEED_USERNAME
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: convapp-secret
                  key: SEED_USER_PASSWORD
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: convapp-secret
                  key: AMQP_HOSTNAME
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: convapp-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_QUEUE
              valueFrom:
                secretKeyRef:
                  name: convapp-secret
                  key: AMQP_QUEUE
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"

  