app:
  name: conv-app
  components: frontend
  image: antonlarichev/conv-app
  tag: "1.2"
  replicaCount: 1
  port: 80
  resources:
    limits:
      memory: "1024Mi"
      cpu: "500m"
    env:
    - name: VITE_DOMAIN
      valueFrom:
        configMapKeyRef:
          name: conv-app-config
          key: VITE_DOMAIN
  appConfig:
    VITE_DOMAIN: conv.test
