apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      components: {{ .Values.app.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.app.components }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            {{ .Values.app.resources | toYaml | nindent 12 }}
          env:
            - name: {{ .Values.app.env.name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: {{ .Values.app.env.name }}
