apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
type: Opaque
data:
  AMQP_USER: ZGVtbw==
  AMQP_PASSWORD: ZGVtbw==
  AMQP_EXCHANGE: ZGVtbw==
  AMQP_HOSTNAME: {{ (printf "%s-clusterip" .Values.api.name) | b64enc | quote }}
  AMQP_QUEUE: ZGVtbw==