apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
type: Opaque
data:
  AMQP_USER: {{ (printf "%s" .Values.rmq.user) | b64enc |}}
  AMQP_PASSWORD: {{ (printf "%s" .Values.rmq.password) | b64enc |}}
  AMQP_EXCHANGE: ZGVtbw==
  AMQP_HOSTNAME: {{ (printf "%s-clusterip" .Values.api.name) | b64enc | quote }}
  AMQP_QUEUE: ZGVtbw==